config/routes.rb
ProyectoIsw611::Application.routes.draw do
  resources :usuarios

  resources :detalle_facturas

  resources :articulos

  resources :facturas

  root 'facturas#index'
  get '/articulos/get_by_code/:codigo'=> 'articulos#get_by_code', as: :get_by_code
  post '/facturas/venta'=> 'facturas#venta', as: :venta

end

app/models/factura.rb
class Factura < ActiveRecord::Base
	belongs_to :usuario, :foreign_key=>"id_usuario"
	has_many :Detalle_factura, :foreign_key=>"id_factura"

	#validates_presence_of :codigo
	validates_presence_of :id_usuario
	validates_presence_of :cliente
	validates_presence_of :fecha
	validates_presence_of :total

	#validates_uniqueness_of :codigo
end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
  end

  # GET /facturas/new
  def new
    @factura = Factura.new
  end

  def venta
    @table=params[:venta][:tablaVenta]
  end

  def receive_factura
     data = JSON.parse(request.body)
     #@activity = Activity.new(params[:fault])
     #@activity.who = data.author    
  end
  # GET /facturas/1/edit
  def edit
  end

  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(factura_params)

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'Factura was successfully created.' }
        format.json { render action: 'show', status: :created, location: @factura }
      else
        format.html { render action: 'new' }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas/1
  # PATCH/PUT /facturas/1.json
  def update
    respond_to do |format|
      if @factura.update(factura_params)
        format.html { redirect_to @factura, notice: 'Factura was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura.destroy
    respond_to do |format|
      format.html { redirect_to facturas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura
      @factura = Factura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_params
      params.require(:factura).permit(:id_usuario, :cliente, :fecha, :total)
    end
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/_form.html.erb
<%= form_for @factura, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :id_usuario, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :id_usuario, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cliente, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cliente, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fecha, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fecha, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                facturas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/facturas/edit.html.erb
<%- model_class = Factura -%>
<%= render :partial => 'form' %>

app/views/facturas/index.html.erb
<div class="well">
  <form id="venta" method="post" action="facturas/venta ">
  <input type="text" name="cliente" placeholder="Cliente" class="span12">
  <table id="tablaVenta" class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Descripción</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <tr class="fila-base" hidden="true">
      <td><input name="codigo" class="codigo input-small" type="text" ></td>
      <td><input name="descripcion" class="descripcion input-xlarge" readonly="true" type="text"></td>
      <td><input name="precio" class="precio input-small" readonly="true" type="text"></td>
      <td><input name="cantidad" class="cantidad input-small" type="number" ></td>
      <td><input name="subtotal" class="subtotal input-small" readonly="true" type="text"></td>
    </tr>  
    <tr>
      <td><input name="codigo" class="codigo input-small" type="text" ></td>
      <td><input name="descripcion" class="descripcion input-xlarge" readonly="true" type="text"></td>
      <td><input name="precio" class="precio input-small" readonly="true" type="text"></td>
      <td><input name="cantidad" class="cantidad input-small" type="number" ></td>
      <td><input name="subtotal" class="subtotal input-small" readonly="true"  type="text"></td>
    </tr>      
  </tbody>
</table>
<button id="sold" class="btn btn-primary" href="facturas/venta">Aceptar</button>
<%= link_to t('.cancel', :default => t("Cancelar")),
                articulos_path, :class => 'btn' %>
</form>
</div>

<script>



$(document).ready(function(){

  $("#sold").click(function(){
    
    var sdata = $("#venta").serialize();

    alert(sdata);

    $.ajax({
      url: "facturas/venta",
      dataType: 'json',
      data: sdata,
      success: function(response) {

      }

  });
  });


  function clonar(){
    if($("table tbody tr:last() td input").val() != ""){
      $("table tbody tr:eq(0)").clone(true).removeClass('fila-base').appendTo("table tbody").removeAttr("hidden");
    }
  }

  $(".codigo").change(function(){
    var ruta = "/articulos/get_by_code/"
    var jsonData;
    var este = $(this);

    $.ajax({
      url: ruta.concat($(this).val()),
      dataType: 'json',
      success: function(response) {
          jsonData = response;

          este.parent().first().next().children().val(jsonData.descripcion);
          este.parent().first().next().next().children().val(jsonData.precio_venta);
          este.parent().first().next().next().next().children().val("1");
          este.parent().first().next().next().next().next().children().val(parseFloat(jsonData.precio_venta));

          clonar();
      }
    }); 
  });


  $(".cantidad").change(function(){

    var subtotal = parseFloat($(this).val()*$(this).parent().prev().children().val());
    $(this).parent().next().children().val(subtotal);

  });

});
</script>

app/views/facturas/new.html.erb
<%- model_class = Factura -%>
<%= render :partial => 'form' %>

app/views/facturas/show.html.erb
<%- model_class = Factura -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id_usuario) %>:</strong></dt>
  <dd><%= @factura.id_usuario %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cliente) %>:</strong></dt>
  <dd><%= @factura.cliente %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @factura.fecha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total) %>:</strong></dt>
  <dd><%= @factura.total %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              facturas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_factura_path(@factura), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              factura_path(@factura),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/facturas/venta.html.erb
<div class="well">
  <%- model_class = DetalleFactura -%>
  <div >
    <input type="text" >
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:id_factura) %></th>
        <th><%= model_class.human_attribute_name(:id_articulo) %></th>
        <th><%= model_class.human_attribute_name(:cantidad) %></th>
        <th><%= model_class.human_attribute_name(:subtotal) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @detalle_facturas.each do |detalle_factura| %>
        <tr>
          <td><%= link_to detalle_factura.id, detalle_factura_path(detalle_factura) %></td>
          <td><%= detalle_factura.id_factura %></td>
          <td><%= detalle_factura.id_articulo %></td>
          <td><%= detalle_factura.cantidad %></td>
          <td><%= detalle_factura.subtotal %></td>
          <td><%=l detalle_factura.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_detalle_factura_path(detalle_factura), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        detalle_factura_path(detalle_factura),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_detalle_factura_path,
              :class => 'btn btn-primary' %>
</div>