config/routes.rb
ProyectoIsw611::Application.routes.draw do
  resources :usuarios

  resources :detalle_facturas

  resources :articulos

  resources :facturas

  root 'facturas#index'
  get '/articulos/get_by_code/:codigo'=> 'articulos#get_by_code', as: :get_by_code
  post '/facturas/venta'=> 'facturas#venta', as: :venta

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_many :Factura, :foreign_key=>"id_usuario"
	has_many :Articulo, :foreign_key=>"id_usuario"
	validates_presence_of :nombre
	validates_presence_of :contrasena
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usuario }
      else
        format.html { render action: 'new' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :contrasena)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for @usuario, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contrasena, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contrasena, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                usuarios_path, :class => 'btn' %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/index.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:contrasena) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.contrasena %></td>
        <td><%=l usuario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      usuario_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_usuario_path,
            :class => 'btn btn-primary' %>

app/views/usuarios/new.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/show.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @usuario.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contrasena) %>:</strong></dt>
  <dd><%= @usuario.contrasena %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              usuarios_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_usuario_path(@usuario), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              usuario_path(@usuario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>